### ISSUE TITLE
Headers missing

### ISSUE THREAD

**Issue by marine-dj** [MoonScript/jQuery-ajaxTransport-XDomainRequest#41]
Hi everyone,

It's strange - when i included jQuery.XDomainRequest, IE discards (some) of the headers. Not as many as if I did it directly through XDR, in which case I wouldn't get any custom headers.
I send off my request as such:

```
$.support.cors = true;
 return $.ajax({
  type: "POST",
  async: true,
  url: _url,
  cache: false,
  crossDomain: true,
  contentType: "application/json; charset=utf-8", // Request
  data: JSON.stringify(_data),
  dataType: "json", // Expected response (json d wrapping xml)
  success: function(msg) {
            if (msg.hasOwnProperty("d")) {
             // Leave the .d behind and pass the rest of 
             //  the JSON object forward.
             _success(msg.d);
            } else {
             // No .d; no transformation necessary.
             _success(msg);
            }
           },
  error: _error,
  beforeSend: function (request)
  {
   request.setRequestHeader("Authorization", "basic " + Base64.encode(userid+":"+pwdhashed));
  }
 });
```

This is the diff between the two (lines shown are what the approach has extra)
I'm not sure about the Origin and Cookie header, but I would like Referer, Authorization and Content-Type.

```
Original:
 Referer: http://bimco.org/common/TestPage.aspx
 Authorization: basic XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX==
 Content-Type: application/json; charset=utf-8
 Cookie: __utma=50439994.1373781375.1408004068.1408371010.1408434254.5; __utmz=50439994.1408004068.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)

jQuery-ajaxTransport-XDomainRequest:
 Origin: http://bimco.org
```
